version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_cobranca_app
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbcobranca_app
      MYSQL_USER: usuario_cobranca_app
      MYSQL_PASSWORD: neguim2024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --authentication_policy=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 123123
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local